version: '3.3'

services:
  app:
    container_name: NoiseRemover
    build:
        context: .
    command: gunicorn --bind 0.0.0.0:10000 main:app --worker-class uvicorn.workers.UvicornWorker
    ports:
      - "10000:10000"